### PR TITLE
Adding docker

### PR DESCRIPTION
**Pull request by samber**
Fixing #1

### CODE REVIEW

**Comment by peey** [comment]
That was quick. Thanks for the PR!

Quick question: were you actually able to test that the node server spins up without errors?

@geekSiddharth could you review this?

**Comment by samber** [comment]
It's crashing because `config/keys` is not found.

image

But mysql is up and app is launched ;)

**Comment by peey** [comment]
I see. I discussed this with @Abhimanyu-Jha 

So `config/keys` is  stores some sensitive information which we won't be uploading to github.

The intended workflow is this:

1. When we're deploying, we pull this repo
2. We add the keys file to the config folder manually
3. We run `docker-compose up`

I don't know if there's a better way to do this. I think ideally it should work, since that file .gitignored so we should be able to pull newer copies of code from repo without conflicts. This means we have to add the keys file just one time

So @samber can you use this dummy [keys.js](https://gist.github.com/peey/e140f0ba8ea8de568f16c9b43487374c) file to see if the server starts?

It'll not be functional since some keys are missing but the server should start

**Comment by samber** [comment]
I got a new error:

image

In the last commit:
- `nodemon` for dev and `node` by default (prod)
- added `config/keys.js.dist`
- for development, you can uncomment lines in `docker-compose.yml`

**Comment by peey** [comment]
Alright.

It seems like we'll have to test this using a file with actual credentials and give you feedback for any other changes which have to be made. 

This might take some time. I hope this doesn't affect your hacktoberfest participation. AFAIK they don't require the PRs to be merged before October ends.

**Pull request closed without merging**
